version: '3.8'

services:
  my-mcp-sse:
    build:
      context: .
      args:
        SAMPLE_SECRET: ${SAMPLE_SECRET}
    image: my-mcp:latest
    container_name: my-mcp-sse
    ports:
      - "8000:8000"
    command: sse
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  # Uncomment to run STDIO mode in a separate container
  # my-mcp-stdio:
  #   build:
  #     context: .
  #     args:
  #       SAMPLE_SECRET: ${SAMPLE_SECRET}
  #   image: my-mcp:latest
  #   container_name: my-mcp-stdio
  #   command: stdio
  #   stdin_open: true
  #   tty: true
